name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ci:
    uses: RoastedHawk/.github/.github/workflows/python-ci.yml@main
    with:
      run-matrix: "['3.11','3.12']"
      cov-threshold: '90'
